In [1]:
import gym_malware as gm

In [2]:
import os

In [3]:
os.path.exists("RL_Features\\adversarial_imports_set.pk")

True

In [4]:
from gym_malware.envs.utils import interface, pefeatures

In [5]:
feature_extract = pefeatures.PEFeatureExtractor()

In [6]:
with open('hello.exe','rb') as f:
    byt = f.read()

In [7]:
feature_extract.extract(byt)

array([2.57712000e+05, 2.80673775e-01, 4.97609735e-02, 1.75389582e-02,
       2.26803564e-02, 2.57031104e-02, 2.82563482e-02, 1.86797666e-02,
       6.74008195e-03, 9.82104054e-03, 4.76500900e-03, 4.02387161e-03,
       8.78888061e-03, 4.31489415e-03, 4.01223071e-03, 5.21512386e-03,
       6.49174272e-03, 4.37309865e-03, 3.13916310e-03, 2.71621034e-03,
       7.88089030e-03, 3.51943254e-03, 2.01775626e-03, 2.37086360e-03,
       2.76665425e-03, 3.37198113e-03, 3.58151735e-03, 1.68017011e-03,
       1.29990066e-03, 1.56376110e-03, 1.51331719e-03, 1.41242938e-03,
       2.77441485e-03, 8.75395791e-03, 2.50667412e-03, 1.38526728e-03,
       9.04110014e-04, 5.57211150e-03, 1.64912771e-03, 1.21841435e-03,
       1.57540200e-03, 2.27385609e-03, 1.97507295e-03, 1.06320233e-03,
       1.14080834e-03, 1.36198547e-03, 6.68575775e-03, 6.85649097e-03,
       4.81545291e-03, 3.28273421e-03, 2.88694356e-03, 2.64248463e-03,
       1.15632955e-03, 4.51278947e-03, 1.19125225e-03, 4.21788663e-03,
      

In [8]:
from gym_malware.envs.utils.interface import EnsembleBlackBoxDetector

In [9]:
import os
import glob

In [10]:
path = "/media/nerdcoder/New Volume/Major Project/Pesiduos/Pesidious/Data/malware/*"

In [11]:
os.path.split(path)

('/media/nerdcoder/New Volume/Major Project/Pesiduos/Pesidious/Data/malware',
 '*')

In [12]:
glob.glob(path)

[]

In [13]:
file_path = r"hello.exe"

In [14]:
with open(file_path,'rb') as f:
    bytt = f.read()

In [15]:
gm.interface.get_score_local(bytt)

0.030372781679034233

In [16]:
# env2 = gm.envs.malenv.MalwareEnv(random_sample=False,output_path="/media/nerdcoder/New Volume/Major Project/malenv/modified")
env2 = gm.envs.malenv.MalwareEnv(random_sample=False,output_path="modified")

In [17]:
env2.action_space

Discrete(4)

In [18]:
a = env2.reset(file_path)
a

Already benign


array([2.57712000e+05, 2.80673775e-01, 4.97609735e-02, 1.75389582e-02,
       2.26803564e-02, 2.57031104e-02, 2.82563482e-02, 1.86797666e-02,
       6.74008195e-03, 9.82104054e-03, 4.76500900e-03, 4.02387161e-03,
       8.78888061e-03, 4.31489415e-03, 4.01223071e-03, 5.21512386e-03,
       6.49174272e-03, 4.37309865e-03, 3.13916310e-03, 2.71621034e-03,
       7.88089030e-03, 3.51943254e-03, 2.01775626e-03, 2.37086360e-03,
       2.76665425e-03, 3.37198113e-03, 3.58151735e-03, 1.68017011e-03,
       1.29990066e-03, 1.56376110e-03, 1.51331719e-03, 1.41242938e-03,
       2.77441485e-03, 8.75395791e-03, 2.50667412e-03, 1.38526728e-03,
       9.04110014e-04, 5.57211150e-03, 1.64912771e-03, 1.21841435e-03,
       1.57540200e-03, 2.27385609e-03, 1.97507295e-03, 1.06320233e-03,
       1.14080834e-03, 1.36198547e-03, 6.68575775e-03, 6.85649097e-03,
       4.81545291e-03, 3.28273421e-03, 2.88694356e-03, 2.64248463e-03,
       1.15632955e-03, 4.51278947e-03, 1.19125225e-03, 4.21788663e-03,
      

In [19]:
a.shape[0]

513

In [20]:
import lief

In [21]:
a =lief.parse(byt)

In [22]:
type(a)

lief._lief.PE.Binary

In [23]:
lief.PE.Builder(a)

In [24]:
state,reward,done,action = env2.step(3)    
state,reward,done,action

lib name : oleaut32.dll , func name : SysAllocString
<class 'lief._lief.PE.Binary'>
Wrote file to modified\hello.exe


(array([2.17600000e+05, 2.31263787e-01, 5.41865809e-02, 1.79090074e-02,
        2.05698529e-02, 3.01654412e-02, 3.30606618e-02, 2.08593750e-02,
        6.36029412e-03, 1.07582721e-02, 5.30790441e-03, 4.48069853e-03,
        9.82536765e-03, 4.62775735e-03, 4.32444853e-03, 5.80422794e-03,
        7.31158088e-03, 4.65073529e-03, 3.49264706e-03, 2.68382353e-03,
        9.05330882e-03, 3.87408088e-03, 2.15992647e-03, 2.62408088e-03,
        3.10202206e-03, 3.73621324e-03, 4.07628676e-03, 1.89797794e-03,
        1.45220588e-03, 1.74172794e-03, 1.72334559e-03, 1.55330882e-03,
        3.21231618e-03, 9.74724265e-03, 2.90441176e-03, 1.59007353e-03,
        1.06617647e-03, 5.45955882e-03, 2.08180147e-03, 1.53033088e-03,
        1.98069853e-03, 2.72977941e-03, 2.11397059e-03, 1.14430147e-03,
        1.10294118e-03, 1.52113971e-03, 7.84466912e-03, 4.14522059e-03,
        5.62959559e-03, 3.45588235e-03, 3.35477941e-03, 2.94117647e-03,
        1.30055147e-03, 4.97242647e-03, 1.10753676e-03, 4.692095

In [25]:
import numpy as np

np.array_equal(state, prev)


NameError: name 'prev' is not defined

In [ ]:
prev = state

In [ ]:
import numpy
numpy.__version__

'1.26.4'

In [ ]:
env2.observation_space

array([2.08960000e+05, 2.45324464e-01, 1.19448698e-02, ...,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00])

In [ ]:
import pickle

In [ ]:
a = pickle.load(open('/media/nerdcoder/New Volume/Major Project/malenv/gym_malware/envs/utils/feature_vector_mapping.pk','rb'))

FileNotFoundError: [Errno 2] No such file or directory: '/media/nerdcoder/New Volume/Major Project/malenv/gym_malware/envs/utils/feature_vector_mapping.pk'

In [ ]:
b = pickle.load(open('/media/nerdcoder/New Volume/Major Project/malenv/RL_Features/adversarial_imports_set.pk','rb'))

In [ ]:
b

{'cryptdll.dll': ['CDLocateRng'],
 'kernel32.dll': ['CopyFileW',
  'SetCurrentDirectoryA',
  'CloseHandle',
  'OpenMutexA',
  'GetPrivateProfileStringA',
  'CreateDirectoryW',
  'GetLogicalDriveStringsW',
  'GetTimeFormatA',
  'CreateMutexW',
  'CompareStringA',
  'SetErrorMode',
  'GetProcAddress',
  'WriteProcessMemory',
  'QueryDosDeviceA',
  'lstrcpynA',
  'GetCommandLineA',
  'GetCurrentThreadId',
  'GetCurrentThread',
  'GetModuleHandleA',
  'GetVolumeInformationW',
  'OpenThread',
  'VirtualAlloc',
  'GetVersionExA',
  'GetACP',
  'LoadLibraryA',
  'InitializeCriticalSection',
  'RaiseException',
  'GetLocaleInfoW',
  'ExitProcess',
  'HeapFree',
  'QueryPerformanceCounter',
  'GetTickCount',
  'GetCurrentProcessId',
  'GetSystemTimeAsFileTime',
  'GetModuleFileNameA',
  'GetLastError',
  'WriteFile',
  'GetCurrentProcess',
  'HeapAlloc',
  'FlushFileBuffers',
  'SetUnhandledExceptionFilter',
  'HeapDestroy',
  'HeapCreate',
  'IsBadWritePtr',
  'VirtualQuery',
  'UnhandledExcep

In [ ]:
a['PhoneBookEnumNumbers']

KeyError: 'PhoneBookEnumNumbers'